name: 'Verify if is Rebased'
description: 'Action for verify if rebased PR, and set label (is-rebased or not-rebased)'
branding:
  icon: 'arrow-up-circle'
  color: 'green'
inputs:
  default-branch:
    description: 'Default branch of repository'
    required: false
    default: ${{ github.event.repository.default_branch }}
  pull-request-branch:
    description: 'Branch of pull request'
    required: false
    default: ${{ github.event.pull_request.head.ref }}
  gh-token:
    description: 'Token with credentials for repository'
    required: true
  reactive:
    description: 'React of push in default branch - default: false'
    required: false
    default: false  

outputs:
  pr-number:
    description: 'The Number of PR'
  rebased:
    description: 'return if pr is rebased with default branch - (true/false)'
runs:
  using: 'node16'
  main: 'dist/index.js'
